### ISSUE TITLE
VidCutter won't open on MacOS Big Sur

### ISSUE THREAD

**Issue by dustinkerstein** [ozmartian/vidcutter-osx#1]
No errors visible on the UI, just silently doesn't open. Where are logs located? I'm happy to get more info if it'd be helpful

**Comment by dustinkerstein** [comment]
When launching from command line I see:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyiboot01_bootstrap.py", line 149, in __init__
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 348, in __init__
OSError: dlopen(OpenGL, 10): image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/OpenGL/platform/darwin.py", line 38, in GL
  File "/usr/local/lib/python3.6/site-packages/OpenGL/platform/ctypesloader.py", line 45, in loadLibrary
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyiboot01_bootstrap.py", line 151, in __init__
__main__.PyInstallerImportError: ("Failed to load dynlib/dll 'OpenGL'. Most probably this dynlib/dll was not found when the application was frozen.", 'OpenGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/travis/build/ozmartian/vidcutter-osx/vidcutter/__main__.py", line 41, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/Users/travis/build/ozmartian/vidcutter-osx/vidcutter/videocutter.py", line 57, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/Users/travis/build/ozmartian/vidcutter-osx/vidcutter/libs/mpvwidget.py", line 30, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/usr/local/lib/python3.6/site-packages/OpenGL/GL/__init__.py", line 3, in <module>

  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/usr/local/lib/python3.6/site-packages/OpenGL/error.py", line 12, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/usr/local/lib/python3.6/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    __bugreport__ = 'https://github.com/ozmartian/vidcutter/issues'
  File "/usr/local/lib/python3.6/site-packages/OpenGL/platform/__init__.py", line 32, in _load
    __author__ = 'Pete Alexandrou'
  File "/usr/local/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 92, in install
  File "/usr/local/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
  File "/usr/local/lib/python3.6/site-packages/OpenGL/platform/darwin.py", line 62, in GetCurrentContext
  File "/usr/local/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
  File "/usr/local/lib/python3.6/site-packages/OpenGL/platform/darwin.py", line 45, in CGL
  File "/usr/local/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
  File "/usr/local/lib/python3.6/site-packages/OpenGL/platform/darwin.py", line 41, in GL
ImportError: ('Unable to load OpenGL library', "Failed to load dynlib/dll 'OpenGL'. Most probably this dynlib/dll was not found when the application was frozen.", 'OpenGL', None)
[39793] Failed to execute script __main__
```

**Comment by massisenergy** [comment]
Exactly same issue here with MacOS 11.3.1, MacBook Pro 13'.
